apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-codis-server-0
  labels:
    bullcloud-pvname: pv-codis-server-0
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /redis-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - okd-node-1
          
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-codis-server-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      bullcloud-pvname: pv-codis-server-0
      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-codis-server-1
  labels:
    bullcloud-pvname: pv-codis-server-1
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /redis-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - okd-node-2
          
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-codis-server-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      bullcloud-pvname: pv-codis-server-1
      
      
      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-codis-server-2
  labels:
    bullcloud-pvname: pv-codis-server-2
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /redis-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - okd-node-3
          
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-codis-server-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      bullcloud-pvname: pv-codis-server-2
      
      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-codis-server-3
  labels:
    bullcloud-pvname: pv-codis-server-3
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /redis-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - okd-node-4
          
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-codis-server-3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      bullcloud-pvname: pv-codis-server-3         